//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: dropsy_airdrop
// ----------------------------------------------------------------------------
pub mod dropsy_airdrop {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for dropsy_airdrop
    pub fn program_id() -> Pubkey {
        pubkey!("GqVDHBaTKkNnLxyKmSSsNqwkthdB77mf31RsZSApRetA")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(authority: Pubkey) -> Self {
            Self { authority }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub protocol_fee: u64,
    }

    impl InitializeInstructionData {
        pub fn new(protocol_fee: u64) -> Self {
            Self { protocol_fee }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeMaster
    // ....................................................................

    /// Main instruction struct for InitializeMaster
    pub struct InitializeMasterInstruction {
        pub accounts: InitializeMasterInstructionAccountMetas,
        pub data: InitializeMasterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeMaster instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeMasterInstructionAccountMetas {
        pub master: AccountMeta,

        pub treasury: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeMaster instruction
    #[derive(Debug, Clone)]
    pub struct InitializeMasterInstructionAccounts {
        pub master: Pubkey,
        pub authority: Pubkey,
        pub treasury: Pubkey,
    }

    impl InitializeMasterInstructionAccounts {
        pub fn new(master: Pubkey, treasury: Pubkey, authority: Pubkey) -> Self {
            Self {
                master,
                treasury,
                authority,
            }
        }
    }

    /// Instruction data for InitializeMaster
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeMasterInstructionData {
        pub args: MasterInitArgs,
    }

    impl InitializeMasterInstructionData {
        pub fn new(args: MasterInitArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for InitializeMasterInstruction
    impl InitializeMasterInstruction {
        fn discriminator() -> [u8; 8] {
            [206u8, 91u8, 246u8, 30u8, 216u8, 101u8, 134u8, 166u8]
        }

        pub fn data(data: InitializeMasterInstructionData) -> Self {
            Self {
                accounts: InitializeMasterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeMasterInstructionAccounts) -> Self {
            self.accounts.master = AccountMeta::new(accounts.master, false);

            self.accounts.treasury = AccountMeta::new_readonly(accounts.treasury, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.master.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: Master
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Master {
    pub authority: Pubkey,

    pub treasury: Pubkey,

    pub token_mint: Pubkey,

    pub protocol_fee: u64,

    pub master_fee_bps: u16,

    pub bump: u8,
}

impl Master {
    pub fn new(
        authority: Pubkey,

        treasury: Pubkey,

        token_mint: Pubkey,

        protocol_fee: u64,

        master_fee_bps: u16,

        bump: u8,
    ) -> Self {
        Self {
            authority,

            treasury,

            token_mint,

            protocol_fee,

            master_fee_bps,

            bump,
        }
    }
}

/// Custom struct: MasterInitArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MasterInitArgs {
    pub protocol_fee: u64,

    pub master_fee_bps: u16,
}

impl MasterInitArgs {
    pub fn new(protocol_fee: u64, master_fee_bps: u16) -> Self {
        Self {
            protocol_fee,

            master_fee_bps,
        }
    }
}

/// Custom struct: MasterInitialized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MasterInitialized {
    pub address: Pubkey,

    pub authority: Pubkey,

    pub treasury: Pubkey,

    pub timestamp: i64,
}

impl MasterInitialized {
    pub fn new(address: Pubkey, authority: Pubkey, treasury: Pubkey, timestamp: i64) -> Self {
        Self {
            address,

            authority,

            treasury,

            timestamp,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
